function drawCardinal() {
    const cardinals = [
        { name: " Jose Advincula", country: " Filipiny" },
		{ name: " Américo Aguiar", country: " Portugalia" },
		{ name: " Carlos Aguiar Retes", country: " Meksyk" },
		{ name: " Fridolin Ambongo", country: " Demokratyczna Republika Konga" },
		{ name: " Anders Arborelius", country: " Szwecja" },
		{ name: " Jean-Marc Aveline", country: " Francja" },
		{ name: " Fabio Baggio", country: " Włochy" },
		{ name: " Philippe Barbarin", country: " Francja" },
		{ name: " Domenico Battaglia", country: " Włochy" },
		{ name: " Giuseppe Betori", country: " Włochy" },
		{ name: " Charles Maung Bo", country: " Mjanma" },
		{ name: " Vincente Bokalic Iglic", country: " Argentyna" },
		{ name: " Josip Bozanić", country: " Chorwacja" },
		{ name: " João Braz de Aviz", country: " Brazylia" },
		{ name: " Leopoldo Brenes", country: " Nikaragua" },
		{ name: " Stephen Brislin", country: " Południowa Afryka" },
		{ name: " Raymond Leo Burke", country: " Stany Zjednoczone" },
		{ name: " François-Xavier Bustillo", country: " Francja" },
		{ name: " Mykoła Byczok", country: " Australia" },
		{ name: " Luis Cabrera Herrera", country: " Ekwador" },
		{ name: " Oscar Cantoni", country: " Włochy" },
		{ name: " Carlos Castillo Mattasoglio", country: " Peru" },
		{ name: " Fernando Chomalí Garib", country: " Chile" },
		{ name: " Stephen Chow Sau-yan", country: " Chiny" },
		{ name: " Manuel Clemente", country: " Portugalia" },
		{ name: " José Cobo Cano", country: " Hiszpania" },
		{ name: " Thomas Collins", country: " Kanada" },
		{ name: " Paulo César Costa", country: " Brazylia" },
		{ name: " Joseph Coutts", country: " Pakistan" },
		{ name: " Blase Cupich", country: " Stany Zjednoczone" },
		{ name: " Michael Czerny", country: " Kanada" },
		{ name: " Sérgio da Rocha", country: " Brazylia" },
		{ name: " Virgilio do Carmo da Silva", country: " Timor Wschodni" },
		{ name: " Pablo Virgilio David", country: " Filipiny" },
		{ name: " Angelo De Donatis", country: " Włochy" },
		{ name: " Josef De Kesel", country: " Belgia" },
		{ name: " John Atcherley Dew", country: " Nowa Zelandia" },
		{ name: " Daniel DiNardo", country: " Stany Zjednoczone" },
		{ name: " Ignace Bessi Dogbo", country: " Wybrzeże Kości Słoniowej" },
		{ name: " Timothy Dolan", country: " Stany Zjednoczone" },
		{ name: " Willem Jacobus Eijk", country: " Holandia" },
		{ name: " Péter Erdő", country: " Węgry" },
		{ name: " Kevin Farrell", country: " Stany Zjednoczone" },
		{ name: " Victor Manuel Fernández", country: " Argentyna" },
		{ name: " Ángel Fernández Artime", country: " Hiszpania" },
		{ name: " Filipe Neri Ferrão", country: " Indie" },
		{ name: " Fernando Filoni", country: " Włochy" },
		{ name: " Sebastian Francis", country: " Malezja" },
		{ name: " Mauro Gambetti", country: " Włochy" },
		{ name: " Juan García Rodríguez", country: " Kuba" },
		{ name: " William Goh", country: " Singapur" },
		{ name: " Arlindo Gomes Furtado", country: " Republika Zielonego Przylądka" },
		{ name: " Mario Grech", country: " Malta" },
		{ name: " Wilton Gregory", country: " Stany Zjednoczone" },
		{ name: " Claudio Gugerotti", country: " Włochy" },
		{ name: " James Michael Harvey", country: " Stany Zjednoczone" },
		{ name: " Jean-Claude Hollerich", country: " Luksemburg" },
		{ name: " Antoine Kambanda", country: " Rwanda" },
		{ name: " Tarcisio Isao Kikuchi", country: " Japonia" },
		{ name: " Kurt Koch", country: " Szwajcaria" },
		{ name: " George Koovakad", country: " Indie" },
		{ name: " Kriengsak Kovithavanij", country: " Tajlandia" },
		{ name: " Konrad Krajewski", country: " Polska" },
		{ name: " Jean-Pierre Kutwa", country: " Wybrzeże Kości Słoniowej" },
		{ name: " Gérald Lacroix", country: " Kanada" },
		{ name: " Chibly Langlois", country: " Haiti" },
		{ name: " Frank Leo", country: " Kanada" },
		{ name: " Augusto Paolo Lojudice", country: " Włochy" },
		{ name: " Cristóbal López Romero", country: " Maroko" },
		{ name: " Thomas Aquino Man’yō Maeda", country: " Japonia" },
		{ name: " Soane Patita Paini Mafi", country: " Tonga" },
		{ name: " Rolandas Makrickas", country: " Litwa" },
		{ name: " Dominique Mamberti", country: " Francja" },
		{ name: " Giorgio Marengo", country: " Mongolia" },
		{ name: " Adalberto Martínez Flores", country: " Paragwaj" },
		{ name: " António Marto", country: " Portugalia" },
		{ name: " Reinhard Marx", country: " Niemcy" },
		{ name: " Dominique Mathieu", country: " Iran" },
		{ name: " Robert McElroy", country: " Stany Zjednoczone" },
		{ name: " José Tolentino Mendonça", country: " Portugalia" },
		{ name: " Francesco Montenegro", country: " Włochy" },
		{ name: " Stephen Ameyu Mulla", country: " Sudan Południowy" },
		{ name: " Gerhard Ludwig Müller", country: " Niemcy" },
		{ name: " László Német", country: " Serbia" },
		{ name: " Vincent Nichols", country: " Zjednoczone Królestwo" },
		{ name: " John Njue", country: " Kenia" },
		{ name: " Kazimierz Nycz", country: " Polska" },
		{ name: " Dieudonné Nzapalainga", country: " Republika Środkowoafrykańska" },
		{ name: " Peter Ebere Okpaleke", country: " Nigeria" },
		{ name: " Juan José Omella Omella", country: " Hiszpania" },
		{ name: " Carlos Osoro Sierra", country: " Hiszpania" },
		{ name: " Philippe Ouédraogo", country: " Burkina Faso" },
		{ name: " Pietro Parolin", country: " Włochy" },
		{ name: " Giuseppe Petrocchi", country: " Włochy" },
		{ name: " Christophe Pierre", country: " Francja" },
		{ name: " Pierbattista Pizzaballa", country: " Włochy" },
		{ name: " Mario Aurelio Poli", country: " Argentyna" },
		{ name: " Anthony Poola", country: " Indie" },
		{ name: " Robert Prevost", country: " Stany Zjednoczone" },
		{ name: " Timothy Radcliffe", country: " Zjednoczone Królestwo" },
		{ name: " Alvaro Ramazzini", country: " Gwatemala" },
		{ name: " Malcolm Ranjith", country: " Sri Lanka" },
		{ name: " Baldassare Reina", country: " Włochy" },
		{ name: " Roberto Repole", country: " Włochy" },
		{ name: " John Ribat", country: " Papua-Nowa Gwinea" },
		{ name: " Francisco Robles Ortega", country: " Meksyk" },
		{ name: " Arthur Roche", country: " Zjednoczone Królestwo" },
		{ name: " Ángel Sixto Rossi", country: " Argentyna" },
		{ name: " Luis José Rueda Aparicio", country: " Kolumbia" },
		{ name: " Protase Rugambwa", country: " Tanzania" },
		{ name: " Stanisław Ryłko", country: " Polska" },
		{ name: " Grzegorz Ryś", country: " Polska" },
		{ name: " Louis Raphaël I Sako", country: " Irak" },
		{ name: " Robert Sarah", country: " Gwinea" },
		{ name: " Odilo Scherer", country: " Brazylia" },
		{ name: " Marcello Semeraro", country: " Włochy" },
		{ name: " Berhaneyesus Demerew Souraphiel", country: " Etiopia" },
		{ name: " Jaime Spengler", country: " Brazylia" },
		{ name: " Leonardo Ulrich Steiner", country: " Brazylia" },
		{ name: " Daniel Sturla", country: " Urugwaj" },
		{ name: " Ignatius Suharyo Hardjoatmodjo", country: " Indonezja" },
		{ name: " Luis Antonio Tagle", country: " Filipiny" },
		{ name: " Orani João Tempesta", country: " Brazylia" },
		{ name: " Baselios Cleemis Thottunkal", country: " Indie" },
		{ name: " Joseph Tobin", country: " Stany Zjednoczone" },
		{ name: " Désiré Tsarahazana", country: " Madagaskar" },
		{ name: " Emil Paul Tscherrig", country: " Szwajcaria" },
		{ name: " Peter Turkson", country: " Ghana" },
		{ name: " Jean-Paul Vesco", country: " Algieria" },
		{ name: " Rainer Woelki", country: " Niemcy" },
		{ name: " Lazarus You Heung-sik", country: " Korea Południowa" },
		{ name: " Mario Zenari", country: " Włochy" },
		{ name: " Matteo Maria Zuppi", country: " Włochy" }

    ];

    const randomIndex = Math.floor(Math.random() * cardinals.length);
    const selectedCardinal = cardinals[randomIndex];

    document.getElementById("cardinal").textContent = selectedCardinal.name;
    document.getElementById("country").textContent = `Państwo: ${selectedCardinal.country}`;
}
